## Compile-time configuration options for chronos that control the availability
## of various strictness and debuggability options. In general, debug helpers
## are enabled when `debug` is defined while strictness options are introduced
## in transition periods leading up to a breaking release that starts enforcing
## them and removes the option.
##
## `tonalliPreviewV5` is a preview flag to enable v5 semantics - see below for
## the strictness checks it adds.
##
## `tonalliDebug` can be defined to enable several debugging helpers that come
## with a runtime cost - it is recommeneded to not enable these in production
## code.
##
## In this file we also declare feature flags starting with `tonalliHas...` -
## these constants are declared when a feature exists in a particular release -
## each flag is declared as an integer starting at 0 during experimental
## development, 1 when feature complete and higher numbers when significant
## functionality has been added. If a feature ends up being removed (or changed
## in a backwards-incompatible way), the feature flag will be removed or renamed
## also - you can use `when declared(tonalliHasXxx): when tonalliHasXxx >= N:`
## to require a particular version.

when (NimMajor, NimMinor, NimPatch) < (2, 2, 10):
  {.error: "tonalli requires Nim >= 2.2.10 (RFC 0012)".}

const
  tonalliHandleException* {.booldefine.}: bool = false
    ## Remap `Exception` to `AsyncExceptionError` for all `async` functions.
    ##
    ## This modes provides backwards compatibility when using functions with
    ## inaccurate `{.raises.}` effects such as unannotated forward declarations,
    ## methods and `proc` types - it is recommened to annotate such code
    ## explicitly as the `Exception` handling mode may introduce surprising
    ## behavior in exception handlers, should `Exception` actually be raised.
    ##
    ## The setting provides the default for the per-function-based
    ## `handleException` parameter which has precedence over this global setting.
    ##
    ## `Exception` handling may be removed in future chronos versions.

  tonalliStrictFutureAccess* {.booldefine.}: bool = defined(tonalliPreviewV5)

  tonalliStackTrace* {.booldefine.}: bool = defined(tonalliDebug)
    ## Include stack traces in futures for creation and completion points

  tonalliFutureId* {.booldefine.}: bool = defined(tonalliDebug)
    ## Generate a unique `id` for every future - when disabled, the address of
    ## the future will be used instead

  tonalliFutureTracking* {.booldefine.}: bool = defined(tonalliDebug)
    ## Keep track of all pending futures and allow iterating over them -
    ## useful for detecting hung tasks

  tonalliDumpAsync* {.booldefine.}: bool = defined(nimDumpAsync)
    ## Print code generated by {.async.} transformation

  tonalliProcShell* {.strdefine.}: string =
    when defined(windows):
      "cmd.exe"
    else:
      when defined(android):
        "/system/bin/sh"
      else:
        "/bin/sh"
    ## Default shell binary path.
    ##
    ## The shell is used as command for command line when process started
    ## using `AsyncProcessOption.EvalCommand` and API calls such as
    ## ``execCommand(command)`` and ``execCommandEx(command)``.

  tonalliEventsCount* {.intdefine.} = 64
    ## Number of OS poll events retrieved by syscall (epoll, kqueue, poll).

  tonalliInitialSize* {.intdefine.} = 32
    ## Initial size of Selector[T]'s array of file descriptors.

  tonalliEventEngine* {.strdefine.}: string =
    when defined(nimdoc):
      ""
    elif defined(emscripten):
      "poll"
    elif defined(android):
      "epoll"
    elif defined(linux):
      "epoll"
    elif defined(macosx) or defined(macos) or defined(ios) or
          defined(freebsd) or defined(netbsd) or defined(openbsd) or
          defined(dragonfly) or defined(haiku):
      "kqueue"
    elif defined(posix):
      "poll"
    else:
      ""
    ## OS polling engine type which is going to be used by chronos.

  tonalliHasRaises* = 0
    ## raises effect support via `async: (raises: [])`

  tonalliTransportDefaultBufferSize* {.intdefine.} = 4096
    ## Default size of chronos transport internal buffer.

  tonalliStreamDefaultBufferSize* {.intdefine.} = 16384
    ## Default size of chronos async stream internal buffer.

  tonalliTLSSessionCacheBufferSize* {.intdefine.} = 4096
    ## Default size of chronos TLS Session cache's internal buffer.

  tonalliUseSink* {.booldefine.} = true
    ## Whether or not to use `sink`.
    ##
    ## https://github.com/nim-lang/Nim/issues/12340 is a particularily serious
    ## bug but it does not affect chronos' usage as long as values are not
    ## moved out of Future (at the time of writing we only move values)

  tonalliStrictReentrancy* {.booldefine.} = defined(tonalliPreviewV5)
    ## Raise an assert if `poll` is re-entered by calling it from an `{.async.}`
    ## function or `callSoon` callback.
    ##
    ## Reentrancy is undefined behavior and generally not allowed in the chronos
    ## runtime - enbling this option will cause a panic if it's detected - this
    ## will become the default in future chronos versions.

  chronosSimulation* {.booldefine.}: bool = false
    ## Build the deterministic simulation substrate (fork-only test
    ## infrastructure): a virtual clock and, in later slices, a hermetic
    ## dispatcher driven by a seeded oracle instead of real OS resources.
    ## Undefined in every release and default build; the substrate is
    ## additive and compiles out entirely when this is `false`.

when defined(debug) or defined(tonalliConfig):
  import std/macros

  static:
    hint("Chronos configuration:")
    template printOption(name: string, value: untyped) =
      hint(name & ": " & $value)
    printOption("tonalliHandleException", tonalliHandleException)
    printOption("tonalliStackTrace", tonalliStackTrace)
    printOption("tonalliFutureId", tonalliFutureId)
    printOption("tonalliFutureTracking", tonalliFutureTracking)
    printOption("tonalliDumpAsync", tonalliDumpAsync)
    printOption("tonalliProcShell", tonalliProcShell)
    printOption("tonalliEventEngine", tonalliEventEngine)
    printOption("tonalliEventsCount", tonalliEventsCount)
    printOption("tonalliInitialSize", tonalliInitialSize)
    printOption("tonalliTransportDefaultBufferSize",
      tonalliTransportDefaultBufferSize)
    printOption("tonalliStreamDefaultBufferSize",
      tonalliStreamDefaultBufferSize)
    printOption("tonalliTLSSessionCacheBufferSize",
      tonalliTLSSessionCacheBufferSize)
    printOption("chronosSimulation", chronosSimulation)

when tonalliUseSink:
  template tonalliSink*(T: type): type = sink T
  template tonalliMoveSink*(v: sink auto): untyped = move(v)
else:
  template tonalliSink*(T: type): type = T
  # Plain `auto`, no `sink`: this branch returns `v` unchanged (no move
  # happens), and on Nim < 2.0.6 `sink auto` fails to match an lvalue
  # seq-element argument for some instantiations.
  template tonalliMoveSink*(v: auto): untyped = v
